import './globals.css';
import { Baloo_2 } from 'next/font/google';
import Provider from '@components/auth/Provider';
import Navbar from '@components/Navbar';
const Baloo = Baloo_2({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={Baloo.className} >
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
